ssize_t readchar(int fd, char *dest);
ssize_t writechar(int fd, char src, bool flush);
char ctoi (char c);
char itoc (char i);
unsigned int digitcount (unsigned int x);
int upow (int base, unsigned int power);
char digit (unsigned int x, unsigned int index);
ssize_t writeuline (int fd, unsigned int src);
ssize_t readuline (int fd, unsigned int *dest);
ssize_t readsline (int fd, void *buf, size_t maxlen);
